addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.13.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.10.4")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.11.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.12.0")
